<?php

namespace app\controllers;

use yii\web\Controller;

class AppController extends Controller
{
    public function beforeAction($action) // метод, выполняемый перед каждым действием
    {
        $this->view->title = \yii::$app->name; // получение заголовка приложения
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    protected function setMeta($title = null, $keywords = null, $description = null) // метод регистрации мета-тегов
    {
        $this->view->title = $title;
        $this->view->registerMetaTag(['name' => 'keywords', 'content' => "$keywords"]);
        $this->view->registerMetaTag(['name' => 'description', 'content' => "$description"]);
    }
}