<?php

namespace app\controllers;

use yii\web\Controller;

class AppController extends Controller
{
    public function beforeAction($action) // метод, выполняемый перед каждым действием
    {
        $this->view->title = \yii::$app->name; // получение заголовка приложения
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}